CREATE DATABASE IF NOT EXISTS app1db;
CREATE USER 'app1user'@'%' IDENTIFIED BY '123';
GRANT ALL PRIVILEGES ON app1db.* to 'app1user'@'%';

FLUSH PRIVILEGES;

SHOW DATABASES;
SHOW GRANTS FOR app1user@%;
